CREATE TABLE public.vehicle(
    vehicleId INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 100, INCREMENT BY 1),
    name VARCHAR(100) NOT NULL,
    colour VARCHAR(100) NOT NULL,
    reg_num VARCHAR(100) NOT NULL,
    vehicle_type INTEGER NOT NULL,
    PRIMARY KEY (vehicleId)
);

CREATE TABLE public.parking_lot(
    lotId INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 100, INCREMENT BY 1),
    floor_count INTEGER NOT NULL,
    PRIMARY KEY (lotId)
);

CREATE TABLE public.parking_floor(
    floorId INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 100, INCREMENT BY 1),
    parking_lot_id INTEGER NOT NULL,
    floor_number INTEGER NOT NULL,
    rows_count INTEGER NOT NULL,
    PRIMARY KEY (floorId),
    FOREIGN KEY (parking_lot_id) REFERENCES parking_lot(lotId)
);

CREATE TABLE public.parking_row(
    rowId INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 100, INCREMENT BY 1),
    floor_id INTEGER NOT NULL,
    row_number INTEGER NOT NULL,
    PRIMARY KEY (rowId),
    FOREIGN KEY (floor_id) REFERENCES parking_floor(floorId)
);

CREATE TABLE public.parking_slot(
    slotId INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 100, INCREMENT BY 1),
    row_id INTEGER NOT NULL,
    slot_number INTEGER NOT NULL,
    slot_size INTEGER NOT NULL,
    vehicle_id INTEGER NOT NULL,
    status INTEGER NOT NULL,
    PRIMARY KEY (slotId),
    FOREIGN KEY (vehicle_id) REFERENCES vehicle(vehicleId),
    FOREIGN KEY (row_id) REFERENCES parking_row(rowId)
);